### ISSUE TITLE
webpack cache error

### ISSUE THREAD

**Issue by mpadge** [mpadge/wasm-next#4]
`npm run build` gives:

``` bash
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
```

and fails. This error has been reported [on StackOverflow](https://stackoverflow.com/questions/73306304/w-webpack-cache-packfilecachestrategy-caching-failed-for-pack-error-unable), on [nextjs](https://github.com/vercel/next.js/issues/27650), and on [webpack itself](https://github.com/webpack/webpack/issues/11908).

**Comment by mpadge** [comment]
So the vercel build of this all works, with the webpack debugger giving first line of:
```
<t> [webpack.cache.PackFileCacheStrategy] restore cache container: 63.285643 ms
```
whereas locally the equivalent first line is:
```
<t> [webpack.cache.PackFileCacheStrategy] No pack exists at /<local>/<path>/...: Error: ENOENT: no such file or directory
```

**Comment by mpadge** [comment]
It seems almost certainly an issue with [webpack cache](https://webpack.js.org/configuration/cache/), where local failures are ultimately caused by:
```
SystemError: Path is a directory: read return ERR_FS_EISDIR (is a directory) /
        at readFile (node:fs:389:5)
        at go$readFile (/.../node_modules/next/dist/compiled/webpack/bundle5.js:1:264604)
        at Object.readFile (/.../node_modules/next/dist/compiled/webpack/bundle5.js:1:264548)
        at FileSystemInfo._readFileHash (/.../node_modules/next/dist/compiled/webpack/bundle5.js:28:295342)
        at /.../node_modules/next/dist/compiled/webpack/bundle5.js:28:1369372
        at Hook.eval [as callAsync] (eval at create (/.../node_modules/next/dist/compiled/webpack/bundle5.js:13:9218), <anonymous>:6:1)
        at AsyncQueue._startProcessing (/.../node_modules/next/dist/compiled/webpack/bundle5.js:28:1369243)
        at AsyncQueue._ensureProcessing (/.../node_modules/next/dist/compiled/webpack/bundle5.js:28:1368818)
        at process.processImmediate (node:internal/timers:511:21)
```

**Comment by mpadge** [comment]
Seems like it's Node 23, as suggested in [this nextjs issue](https://github.com/vercel/next.js/issues/71911). I was able to reproduce the error with Node 23 in clean docker containers of both Ubuntu and Archlinux using `create-next-app@latest`, although simply installing `nvm` then gave different results even for same version of Node, so it's not just that. It's all too complicated for now, and can be solved for the moment by simply downgrading to Node 22.
